### ISSUE TITLE
Game crashes whenever I do a dice roll in conversation 

### ISSUE THREAD

**Issue by BitterXsweet** [Norbyte/bg3se#272] opened 2024-02-17 13:41 UTC
after the new update with the script extender, my game crashes every time their is a dice roll in conversation

**Comment by FLOYDAKING** [comment] 2024-02-17 15:54
Same here

**Comment by MedoHaleem** [comment] 2024-02-17 20:01
Go through all yours mods in Mod Manager and update each one of them, I was experiencing the same issue but it got fixed by updating my mods, I wish I could say which one as I update it all of them at once.

**Comment by DexManzana** [comment] 2024-02-18 16:32
I have the same problem, i update all my mods and the problem still here

**Comment by Norbyte** [comment] 2024-05-10 08:58
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.

**Closed by Norbyte** 2024-05-10 08:58 UTC
