### ISSUE TITLE
Any update on the extension? 

### ISSUE THREAD

**Issue by sirkingjamz** [Norbyte/bg3se#163] opened 2023-11-14 23:33 UTC
Before anyone jumps on me I completely understand that people have lives and have other priorities in their lives and making mods for the most part is a hobby for most. I was just wondering how close or far the devs might be to a fix? 2 weeks isnt so bad, but going on 3 weeks and no word is tense.

I do not want to harass the Devs or anyone directly connected to this mod, thats not my intention. A small even "where not done yet" is fine enough lol. I really didn't notice how many mods actually relied on this as a dependency until it broke in the latest update. Rolling back an update is obviously still an option and one I'm still considering but want to wait until I can get a rough timeline on this update.

I hope all the devs are doing well with the greatest health, I want to also thank them for making this community even possible so quickly, literally without there discoveries (alongside the community) the modding landscape for this game wouldve been so very dry until Larian released actual mod tools. So again with the fullest of my heart thank you Norbyte (and team if there is one) and the community uses of the mods and mod devs using the mod, thank you as well. Like me you are most likely as anxious for this update as well.

thank you, peace and love.

**Comment by FallenStar08** [comment] 2023-11-15 17:10
What

**Comment by Anesah** [comment] 2023-11-15 19:52
I have a slightly different question, nonetheless related bc it sounds like you're in the same boat as me. Is the script extender expected to throw the "no script extender exists for version blah.blah.blah" after any/every update? I'm not trying to sound impatient either, I'm just curious if other people have found a way to use the current release of the incredible SE with patch 4/hotfix 10 and I/we are the ones doing something wrong. I'm not here to hassle anybody, but knowing how loud and impatient people tend to be in the wild internet, I expected a thousand one-line posts from people without regard for the development process and people's real lives complaining about how they can't play their favorite game the way they want and "ITS ALL YOUR FAULT!" Having not found those kinds of messages has made me self-conscious that something is wrong with my mod setup and forced me to wonder if other people have a work-around.

Thanks for the incredible work you guys do.

**Comment by sirkingjamz** [comment] 2023-11-15 21:46
> I have a slightly different question, nonetheless related bc it sounds like you're in the same boat as me. Is the script extender expected to throw the "no script extender exists for version blah.blah.blah" after any/every update? I'm not trying to sound impatient either, I'm just curious if other people have found a way to use the current release of the incredible SE with patch 4/hotfix 10 and I/we are the ones doing something wrong. I'm not here to hassle anybody, but knowing how loud and impatient people tend to be in the wild internet, I expected a thousand one-line posts from people without regard for the development process and people's real lives complaining about how they can't play their favorite game the way they want and "ITS ALL YOUR FAULT!" Having not found those kinds of messages has made me self-conscious that something is wrong with my mod setup and forced me to wonder if other people have a work-around.
> 
> Thanks for the incredible work you guys do.

Yeah I don't want to sound like an impatient person incapable of understanding peoples lives and that this is more of a hobby rather then a 9-5 job, I just want to know what the progress is on the extender and if i should just downgrade to an old working patch or if the update is close enough that (I really dont mind) wait for the updated files. 

Since someone understood what i was saying im going to ignore the "what" comment and assume they would be one of those people that dont understand the concept of being polite and appreciating all the hard work put into something, when asking people to do things for you when you can't yourself aka updating this script extender. 

Any update or insight to how the development of this mod is going would be much appreciated! If they have a discord or something like that the community can join could someone point me in the right direction, or if they have a blog or some sort of forum (besides here on git) that they share more insight to the progress? I can see that the files are being updated on this repository almost daily but that's still not a clear idea of the progress and state of the current build.

Thanks in advance for any input :)

**Comment by FallenStar08** [comment] 2023-11-16 02:25
I think I wasn't clear the first time : **What**? 

SE was updated like a single day after patch4 dropped. 

Anyway if you want to ask Norb about super important things such as updating the thing that was updated days ago you can find him in Larian's discord. 

If SE somehow doesn't work for you that's a whole different issue.

**Comment by Anesah** [comment] 2023-11-16 04:28
Okay, so I MUST be missing something. Patch 4 was released through steam on 11/3, but the current release of the script extender says it was uploaded 11/28, which was the day hotfix 9 was released. How is it possible it was updated days before patch 4 was released? Actually, honestly, that question isn't that important, but now I need to go figure out why my mod manager and my game both throw errors saying that no script extender exist for the current version.

I've spent hours re-downloading steam depots thinking that it was my game version stopping the extender from working, but that seems not to be the case. And, in fact, restoring hotfix 9 has not stopped my game from throwing the "script extender does not exist" message. Let me screenshot what I mean...I'll be back.

**Comment by Anesah** [comment] 2023-11-16 04:48
Well, now I feel absolutely stupid. While the error message I was describing still happen intermittently, and the mod manager claims that there is no SE installed, I realized that one of the mods that ostensibly requires the SE to work is...working fine. I turned this into a bigger problem than I thought. Frustrating.

I guess I shouldn't trust my own eyes...

**Comment by FallenStar08** [comment] 2023-11-16 17:03
What you install is the updater (it's in the name) SE updates when you launch the game and you should always have the latest version.

**Comment by ChuckHeatherly** [comment] 2023-11-16 18:30
My latest copy of the ACTUAL script extender DLL is in here:

C:\Users\<username>\AppData\Local\BG3ScriptExtender\ScriptExtender\9.0.0.0_773427a2dc83fc58b4f041e5d687d0f246994c79e26edd23f2a70a24944c9926\BG3ScriptExtender.dll

And is timestamped Sunday, ‎November ‎5, ‎2023, ‏‎8:06:26 PM. Does anyone else have a newer version?

This is the location of the files that the DWrite.dll file in the BG3 bin folder remotely downloads into the above location (giant string of hex digits different for each new version of course).

**Comment by Anesah** [comment] 2023-11-16 21:44
That tidbit about this file being an updater and the location where the download actually occurs lead me to a complete answer.

On my PC, the script extender directory in AppData was empty. I suspect the mods that were working that still claimed to require SE either don't actually require it and were just being overzealous with dependencies or only certain parts of the mods require them and not having gone past character creation with the error being thrown limited my understanding.

The real problem that prevented the SE update/download was my antivirus. I did finally get a screenshot of the error message I was getting when starting BG3 with DWrite present in the "BG3/bin" directory but my antivirus blocking it, though now that I know the antivirus was the problem, I don't have any issues to solve. When starting the game without my antivirus active, the console window for the updater opens as expected instead of displaying the error I linked.

[https://drive.google.com/file/d/1ldu_urqngENkhgcfTdlDUTZJQi3aLs7E/view?usp=sharing](url)

![bg3mm_seMissingError](https://github.com/Norbyte/bg3se/assets/11458741/7ef8e047-4897-4b34-a3a4-4068a777949d)

**Comment by ChuckHeatherly** [comment] 2023-11-16 22:13
@Anesah glad to hear the info helped you! The only reason I even found that folder is, as a former software tester, we are very curious about what gets put into AppData\Local and \Roaming. Otherwise I don't know how you'd know it was there except by reading the code, and I wouldn't wish reading C++ on my worst enemy :D

**Comment by queenizunia** [comment] 2023-11-17 15:45
I am not running into any issues like those presented but i am confused as to what is happening to the release because the Release page is dated 10/28, and when I check for updates via the BG3MM, It says I have the latest, which is v8. Others are saying that this is not updated yet, and others are saying its been updated for weeks. Some users have access to v9 and seem to be running into some issues and others like myself don't have access anywhere to it. I'm not here to complain or anything, I completely understand this is a money free process that Norbyte is doing out of kindness and interest in this project and I'm certainly not looking to complain or rush, I'm just curious as to the current state of things since I am finding conflicting info even in my social circle - my friend somehow has v9 but her game has not been playing nicely with patch 4 and I only have access to v8 and have not updated my game - solely because I'd seen that script extender was not yet updated. There are conflicting reports on Nexus too with most users saying that this has not updated yet.

**Comment by Anesah** [comment] 2023-11-17 18:05
I can confirm the script extender works with the current, most updated version of the game. If when you run your game with the "console enabled" version of the script extender updater--which is what's actually available on the release page--and you see the console pop up when you launch the game, your script extender should have no problem updating once you've patched the game.

If you are getting the error message I posted when you launch, try checking the directory that Chuck specified to see if your ACTUAL script extender is present. If it isn't, then something is blocking the download. In my case, it was an antivirus, but I doubt that's the only thing that can go wrong. 

I made the same error that many people on various forums did--I saw that the script extender UPDATER that is available here wasn't updated following 11/28 and assumed that meant the script updater itself had not been updated, either. This is not correct. The file you download (and hopefully properly install in your BG3/bin folder) is only an update tool that checks to see if you have the latest script extender for your game version and, if not, downloads it, by default to the directory that Chuck pointed out:

C:\Users\[username]\AppData\Local\BG3ScriptExtender\[yadda yadda]

Because the files that the updater downloads for you are not the same as those contained on the release page, you should disregard the date of the updater tool (because its been coded to be forwards-compatible with patches, because all it does is check for your current game version and then checks if that game version has a compatible bg3se available, and fetches it for you.

@ChuckHeatherly I'm an ancient software engineer who has barely used his skills in the last decade, and I'm ashamed that I let this slip past me. However, I have the same reaction to being forced to wade through C++ code. Thanks for taking one for the team :)

**Comment by ChuckHeatherly** [comment] 2023-11-17 18:19
@Anesah don't feel bad, seriously. I can understand why they don't document the AppData\Local location for the real SE files. Users (and that includes me) will fuck up anything given a chance! And then they'd have to add code to deal with things like files/directories getting deleted or whatever. Still, I'm sure it's not helping the dev team that the entire world is either coming here or the Nexus page screaming that the SE hasn't been updated since 10/28.

**Comment by Anesah** [comment] 2023-11-17 18:36
@ChuckHeatherly The most hilarious/depressing part is that I am pretty sure I ran into this same problem just after 1.0 launched. I must have found a post somewhere detailing how the updater worked and I remember having to crawl through %appdata% to find an old bg3se and delete it, disable my AV, and got it working again. Then I repeated the same errors and took much longer to reach a solution this second round. I totally understand why people are getting lost/giving up due to the misinformation circulating out there. In fact, that misinformation probably lead to the original source that helped solved my issue months ago being buried beneath more recent, less helpful stuff.

I studied what I did in college because at the time I really thought the internet could save us from ourselves. What a fool, lol.

**Comment by SheeraDarkphoenix** [comment] 2023-11-17 23:06
I finally got it to somewhat work with the console/debugger. Just some problems loading some of the mods for CC and Gameplay that required the most recent SE to properly work. New version is listed in the debugger console, but it's not a complete version of the Extension. Once the SE is fully updated, I can get it added. I have used both BG3MM and Vortex, and got the same result. I use Vortex for downloading and updating the mods, BG3MM for keeping the SE updated so that I can use the mods that I download to Vortex to use in BG3MM.

**Comment by bowm8935** [comment] 2023-11-18 01:09
Hi so... if I follow the directions to the folders that @ChuckHeatherly and @Anesah list, I get stuck without a Data folder. I've run into this issue before - I don't know if it's because I have it through Steam? But this is where I stall:

![image](https://github.com/Norbyte/bg3se/assets/151283925/f2310cc1-0285-44b9-a029-4c42b98d5db4)

If I go through the other route into the Data folder  (C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\Data), there is no Local. Any suggestions on where I should be looking?

**Comment by Anesah** [comment] 2023-11-18 01:48
The appdata folder is hidden by default if you haven't changed your Windows file options. Try typing %appdata% into the bar that says "this pc > windows(c:) > [etc]". Just clear the file location that it changes into when you click on the text bar, and type %appdata% . That will bring up the hidden folder you can't find.

Windows intentionally dumbs down lots of features to make the experience easier for people who just want a computer to work without confusing them. If you want to change this for your whole system, go to file, then options. Then, on the view tab, there will be lots of options for changing the level of hidden information that Microsoft wants users not to have to think about, including displaying hidden files and folders and displaying extensions for known file types.

**Comment by SwissFred57** [comment] 2023-11-18 07:53
V10 is on the way i think will be released soon as the IDE is updated to V10

**Comment by ChuckHeatherly** [comment] 2023-11-19 03:35
@SwissFred57 what is the IDE?

**Comment by SwissFred57** [comment] 2023-11-19 07:27
![image](https://github.com/Norbyte/bg3se/assets/123299068/347f9d6e-492d-40e3-bffe-49e9ab1991cf)

**Comment by GeneralShadowMC** [comment] 2023-11-20 23:43
As far as pinpointing the location of the DLL files that the Mod Manager installs, I don't suppose by some deranged miracle anyone might know where to find that in the labyrinthine hellscape that is the SteamOS? Because I've pretty much been perpetually stuck, unable to update this thing to its most-up-date version (apparently now I don't even have version ONE installed according to some mods), so I can only assume I have to just gut out wherever folder it's being held in and stick to the website install.

**Comment by SwissFred57** [comment] 2023-11-21 07:18
you should look for DWrite.dll at the Bin location of the Game
eg. C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin
and delete all refferences to it 
also all instances of BG3SE-Updater-xxxxx.zip

**Comment by Norbyte** [comment] 2024-05-10 08:41
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.

**Closed by Norbyte** 2024-05-10 08:41 UTC
