### ISSUE TITLE
Unable to parse manifest: * Line 1, Column 1

### ISSUE THREAD

**Issue by ghost** [Norbyte/bg3se#80] opened 2023-09-27 21:48 UTC
Unable to parse manifest: * Line 1, Column 1
  Syntax error: value, object or array expected.
after hotfix 7

**Comment by cahyanugraha12** [comment] 2023-09-28 08:42
Encounter the same message on the initial loading screen.

It doesn't seem to affect the game adversely, but it is still worrying.

**Comment by piccololye** [comment] 2023-10-01 11:08
I have this too - only installed script extender yesterday, was fine but now have this. Game on latest version

**Comment by Norbyte** [comment] 2023-10-01 16:11
If you still have this issue, can you open this URL and post here what you get?
https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json

**Comment by komori** [comment] 2023-10-01 16:43
> If you still have this issue, can you open this URL and post here what you get? https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json

Getting same issue as OP, so I tested the manifest URL from my desktop where I run BG3. In browser (Firefox) it loads up what appears to be a clean/complete/in-tact json file which outlines all of the [minimum game version] : [extender version] pairs with the ".package" URLs, starting with the game version 4.36.35.601 and the "Version too old...only supports v1" error message. 

For good measure, I took both the manifest URL you posted and one of the v5 .package URLS from the manifest and tested them with wget in powershell and both URLs resolved successfully and resulted in an un-corrupted complete files on my local drive. (though, I don't have any program that opens .package file extensions).

Here's a screencap if there's some detail you're looking for with the manifest file:
https://i.imgur.com/S200owO.png

**Comment by piccololye** [comment] 2023-10-01 19:10
> If you still have this issue, can you open this URL and post here what you get? https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json

[Unable to parse manifest.txt](https://github.com/Norbyte/bg3se/files/12778002/Unable.to.parse.manifest.txt)

**Comment by zz13254235** [comment] 2023-10-03 14:51
I'm also suddenly encountering this, was playing fine all day yesterday, then suddenly today i got this error.
Anyone found a fix yet?

**Comment by zz13254235** [comment] 2023-10-03 15:02
it suddenly started working again after 10m.

**Comment by Artoriasu** [comment] 2023-10-05 21:32
it should be fixed now

**Comment by komori** [comment] 2023-10-07 08:33
My issue evolved a bit into the general connectivity failure with the updater aborting the game launch sequence with the, "No connection."/"Can't retrieve manifest." errors. I can pop a non-admin console from the BG3's /bin directory and successfully download manifest JSON w/curl or wget, so it may just be yet another case of Windows doing something strange with the updateer process' network requests.

I resolved the game launch failures by performing the updater's tasks by hand:
-Download Manifest.json and_v5.0.0.0-7ed6be7f9dd9bc33d4f990e5d45b81ca6fdb046c446ccc8774665096f803b132.package_
-Placed them both in C:\Users\<username>\AppData\Local\BG3ScriptExtender
-Unpacked the package to a new directory: C:\Users\<username>\AppData\Local\BG3ScriptExtender\v5.0.0.0-7ed6be7f9dd9bc33d4f990e5d45b81ca6fdb046c446ccc8774665096f803b132
-Swapped out the BGSE updater for the "Manual" version that doesn't attempt any connection.

Game is starting fine now and running a pile of mods leveraging the script extender.

**Comment by Eudoxxi** [comment] 2023-10-28 01:01
i Just started Trying mods out and ran into this issue cant seem to find a fix .

> If you still have this issue, can you open this URL and post here what you get? https://bg3se-updates.norbyte.dev/Channels/Release/Manifest.json

{
    "ManifestMinorVersion" : 1,
    "ManifestVersion" : 1,
    "NoMatchingVersionNotice" : "Game version too old for Script Extender, make sure you're on Patch 2 or later.",
    "Resources" : 
    [
        {
            "Name" : "ScriptExtender",
            "Versions" : 
            [
                {
                    "BuildDate" : 133373499899139335,
                    "Digest" : "1f1ba2f9c64a00204cb05410cd7364e13532e2ed9e2cdffbd498b24b49a9e1b7",
                    "MinGameVersion" : "4.36.35.601",
                    "Notice" : "This game version is too old and only supports Script Extender v1; make sure you're on Patch 2+ for newer versions",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v1.0.0.0-1f1ba2f9c64a00204cb05410cd7364e13532e2ed9e2cdffbd498b24b49a9e1b7.package",
                    "Version" : "1.0.0.0"
                },
                {
                    "BuildDate" : 133383242904791143,
                    "Digest" : "68e6fcbd59647a0b233d8d1ff288be1c23b4b41fe7635081e71d62fd6538f9d1",
                    "MinGameVersion" : "4.36.86.210",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v2.0.0.0-68e6fcbd59647a0b233d8d1ff288be1c23b4b41fe7635081e71d62fd6538f9d1.package",
                    "Version" : "2.0.0.0"
                },
                {
                    "BuildDate" : 133386623580900355,
                    "Digest" : "d4c825981c6af6ad65d00aa63804b165f639f9c2b29b0780955027353279d7eb",
                    "MinGameVersion" : "4.36.86.210",
                    "Signature" : "31534742dfd4a4aa7f641de56bbf5e7d43e16842b6858ecdd506e4c53c71f312cf06b8d7669e65449d50dd89d4897d3a9c4f9071c14a7596ae8c54f16590ad358253173a0161c51b00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v3.0.0.0-d4c825981c6af6ad65d00aa63804b165f639f9c2b29b0780955027353279d7eb.package",
                    "Version" : "3.0.0.0"
                },
                {
                    "BuildDate" : 133406171334238741,
                    "Digest" : "18b315b48303a7b4356e064f270c1de7669a25e0422fd498ba2348d2a12fc0ee",
                    "MinGameVersion" : "4.37.32.833",
                    "Signature" : "3153474203f93aef55cfcb4476efa8a87a906d46ef62ca9fae88484955e4bc7ef1cf26382bf9103d99b039a7c9e821181a9895e7bd5e33b8a2d9dd3a2fc16b1ee7b3a336017f4b1e00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v6.0.0.0-18b315b48303a7b4356e064f270c1de7669a25e0422fd498ba2348d2a12fc0ee.package",
                    "Version" : "6.0.0.0"
                },
                {
                    "BuildDate" : 133383249107178056,
                    "Digest" : "90b5ade604a3a35454d059c21fde458133507cfc0ad2a56a6aa8d0f1f3b810ff",
                    "MinGameVersion" : "4.36.86.210",
                    "Signature" : "3153474252dd0d386c5dd301d3d471219881924caabf6185f2e6bfd0508973bea251ee31131c318c09e4897be63cc98a498269dc698541c8195042087dff597cb63577fa01279c1b00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v2.0.0.0-90b5ade604a3a35454d059c21fde458133507cfc0ad2a56a6aa8d0f1f3b810ff.package",
                    "Version" : "2.0.0.0"
                },
                {
                    "BuildDate" : 133395309788652430,
                    "Digest" : "1fb1c8e3262b70b3341be370ff42529a18e2076bf2bcfdb61a195713d64b64b2",
                    "MinGameVersion" : "4.36.86.210",
                    "Signature" : "315347421b32017c0a759082120448f65a0555ddd8c4c3a91e955892555e1ea4a91fc6242f3ab3b1693481da03373a8f8093efe8d480a1dffbf0de855fabb025aadc24bf01471a1d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v4.0.0.0-1fb1c8e3262b70b3341be370ff42529a18e2076bf2bcfdb61a195713d64b64b2.package",
                    "Version" : "4.0.0.0"
                },
                {
                    "BuildDate" : 133383335810096929,
                    "Digest" : "64ab2ed715fbcf794bb66a8f755d8ed46c236623776c6f2458de22ba8f9a6cfb",
                    "MinGameVersion" : "4.36.86.210",
                    "Signature" : "31534742173c6beafe1de3929dc3dc96c6ffd765e9a48e03f62f24fccdb72db6a934d1fb61ae9badebdb347b087a3160f0dffd2970e744b575836cb7cbc7c6b231f35c1b01939b1b00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v2.0.0.0-64ab2ed715fbcf794bb66a8f755d8ed46c236623776c6f2458de22ba8f9a6cfb.package",
                    "Version" : "2.0.0.0"
                },
                {
                    "BuildDate" : 133395311680536381,
                    "Digest" : "2ca0753520142d23217e005eb64823e393e09dd4e7d3128847b34b7655727c30",
                    "MinGameVersion" : "4.36.86.210",
                    "Signature" : "31534742f74946bd8cd9688e20c80291af5d1fc49a73c1182f1354985a818d71bf19b31f5d89a005ac60169588af78e3738a996454207be1357195a8cdbfe9b7d469d0c9012e1b1d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v4.0.0.0-2ca0753520142d23217e005eb64823e393e09dd4e7d3128847b34b7655727c30.package",
                    "Version" : "4.0.0.0"
                },
                {
                    "BuildDate" : 133395340271022000,
                    "Digest" : "4cefa525910658726ea3834fbc0e35da29486d5bd4a1a64a9d2e7eca25f4b934",
                    "MinGameVersion" : "4.36.86.210",
                    "Signature" : "3153474248a139c5dc40c0f750c039188167dd1880f3832c1328067735ac7550d9763f9f8302aa91249f28236a3293d9c162e055571fa337916fc453537afffd56e5b00c012b1b1d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v4.0.0.0-4cefa525910658726ea3834fbc0e35da29486d5bd4a1a64a9d2e7eca25f4b934.package",
                    "Version" : "4.0.0.0"
                },
                {
                    "BuildDate" : 133395362367759373,
                    "Digest" : "1b9fd07864ab8f818306e6b32611936e9aacc51909c0ee8b67450b5231bcb8e0",
                    "MinGameVersion" : "4.36.86.210",
                    "Signature" : "31534742f16050ca5378c8063aca048ba635e91aef277de04e9c6d5b9517c3a2bd341f4b00e168b18af8ae63e810b686f5c4c68cc11d0778a3cff0d8c9646c847968bb69012a1b1d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v4.0.0.0-1b9fd07864ab8f818306e6b32611936e9aacc51909c0ee8b67450b5231bcb8e0.package",
                    "Version" : "4.0.0.0"
                },
                {
                    "BuildDate" : 133395363901692597,
                    "Digest" : "f3d1373ed32410420970e8a9d37e83e3842e095988f2bcaa63c0a24b10962000",
                    "MinGameVersion" : "4.36.86.210",
                    "Signature" : "31534742691de6dc30766eca46bb1f9d33626d511d05c443506aa696ec17a17a077c921273c070343bb8b45623aac981315ab6170219f8fb15362db01b279b326bcb66df01291b1d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v4.0.0.0-f3d1373ed32410420970e8a9d37e83e3842e095988f2bcaa63c0a24b10962000.package",
                    "Version" : "4.0.0.0"
                },
                {
                    "BuildDate" : 133395406236314074,
                    "Digest" : "b7543ed53ed54c1949f654c3773cffad5e33c9301c5483e9fb202d50b6f1e3a4",
                    "MinGameVersion" : "4.36.86.210",
                    "Signature" : "3153474282c87f89c34fc17b1b54aef3c6d59a0d515cae8d1c197f322c82be6f4f3ad8ce9e92e256827c406edd76eb2d85f4cc09c4314b7e8c1b1abacc1bd04a337aba3001c41b1d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v4.0.0.0-b7543ed53ed54c1949f654c3773cffad5e33c9301c5483e9fb202d50b6f1e3a4.package",
                    "Version" : "4.0.0.0"
                },
                {
                    "BuildDate" : 133398681716987779,
                    "Digest" : "a923c549ec956cacc20768e281083fc50bdb552a34113118237d2082a7e2f366",
                    "MinGameVersion" : "4.37.32.833",
                    "Signature" : "315347420b25b695e8011f9d71240fdf3fb3e60a55ac1bb9c445c87c70da5646d361b85f07c653b7d8ece250f357fe973a546deb59c3114c47b701deb3a8ce8220ac2a3801a8cf1d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v5.0.0.0-a923c549ec956cacc20768e281083fc50bdb552a34113118237d2082a7e2f366.package",
                    "Version" : "5.0.0.0"
                },
                {
                    "BuildDate" : 133398718991945947,
                    "Digest" : "4a181c1fbb99be65326ce880dde17ccfb398bdce53c6cd98527ac1ba6d9d9a49",
                    "MinGameVersion" : "4.37.32.833",
                    "Signature" : "315347422afaf3d6d8a8f72df34cf33bc8a937b1dfa80aacc0d1c17c20a68867085c7c01c3d4e0dc4c17f0738e2716a820f7a57cd5d68c273dc7f08f9ccdb26e14bd9f1a0192cf1d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v5.0.0.0-4a181c1fbb99be65326ce880dde17ccfb398bdce53c6cd98527ac1ba6d9d9a49.package",
                    "Version" : "5.0.0.0"
                },
                {
                    "BuildDate" : 133398755799286425,
                    "Digest" : "dc6ae38d30f75451ba02ed6904f20608566d5c4dad1cf076d3f582b16bb874f0",
                    "MinGameVersion" : "4.37.32.833",
                    "Signature" : "31534742cf2e7a32bdd969c7d72e4dcc253ff73ea31efaa99229ca0f91c4e4853a1bd78ee8ac30dfa4c85ec24f44baf602c88f0bbd9e95ba241793efed52f309cb45e585015ed01d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v5.0.0.0-dc6ae38d30f75451ba02ed6904f20608566d5c4dad1cf076d3f582b16bb874f0.package",
                    "Version" : "5.0.0.0"
                },
                {
                    "BuildDate" : 133398778767091370,
                    "Digest" : "860fd3d31e70e16dc7f9d4ef44e87930764d0cb206682fffc5bcc80e6b7323e4",
                    "MinGameVersion" : "4.37.32.833",
                    "Signature" : "3153474277d06af52bc92be3433c1999ea6c546e579a0da72ca6a7d34470fb07bc2cdfd86bdf77c2de2b0f562ce71e7ac9b3873433508b0591932dced4424da71de4660b015ed01d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v5.0.0.0-860fd3d31e70e16dc7f9d4ef44e87930764d0cb206682fffc5bcc80e6b7323e4.package",
                    "Version" : "5.0.0.0"
                },
                {
                    "BuildDate" : 133399336766270680,
                    "Digest" : "b05cbdf3d6d2386f2f0d233d7ce67e7d49ab8773150cf36bc0b40902e8decf12",
                    "MinGameVersion" : "4.37.32.833",
                    "Signature" : "3153474210180f6bfa50dfa12c9d20ead94ade5ecc573d0317c022c33a4b2aff9af2b61795054b176c134cd743dfb0be2b0d8d73f9a2ed9579315cbcc12501d8705bf519012fd01d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v5.0.0.0-b05cbdf3d6d2386f2f0d233d7ce67e7d49ab8773150cf36bc0b40902e8decf12.package",
                    "Version" : "5.0.0.0"
                },
                {
                    "BuildDate" : 133400531768779887,
                    "Digest" : "f5b84cae3926e01ae89dc75ce048706d9e3d11fc23d8cd0b21259a660f7f3d6e",
                    "MinGameVersion" : "4.37.32.833",
                    "Signature" : "3153474220e073c581ef3519180c3bffadbc567d54ee71e627111a30d3fa1efbe1027811d95862196ba7c1c2350c3f96f60960457876259e1a6b4cb364ce83c821648fc3012fd01d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v5.0.0.0-f5b84cae3926e01ae89dc75ce048706d9e3d11fc23d8cd0b21259a660f7f3d6e.package",
                    "Version" : "5.0.0.0"
                },
                {
                    "BuildDate" : 133401290899767194,
                    "Digest" : "7ed6be7f9dd9bc33d4f990e5d45b81ca6fdb046c446ccc8774665096f803b132",
                    "MinGameVersion" : "4.37.32.833",
                    "Signature" : "315347421a6d7f34df98d7d29a94a50ea091a6df0dcf830f8e00bb3f2bc60d6372aba5ade0223f6f965594e48d7320daeb2f274a52cee34f746cac10ae0341614cd256fe0180f41d00",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v5.0.0.0-7ed6be7f9dd9bc33d4f990e5d45b81ca6fdb046c446ccc8774665096f803b132.package",
                    "Version" : "5.0.0.0"
                },
                {
                    "BuildDate" : 133412365185305027,
                    "Digest" : "26b1b15c7a93bafcaf061c08facd485e0bc205f332f9462852c35debe9b1c253",
                    "MinGameVersion" : "4.37.32.833",
                    "Signature" : "31534742d4257ff3c82c3dc35ab683a5bd1f578ba4980b6a0c32be63dca8b75ec59ba7df7c4239cd17669080cd20810a378364bb9b0010ea571c0524ca4067583906c0fc0102312100",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v7.0.0.0-26b1b15c7a93bafcaf061c08facd485e0bc205f332f9462852c35debe9b1c253.package",
                    "Version" : "7.0.0.0"
                },
                {
                    "BuildDate" : 133412571402268508,
                    "Digest" : "d52f9b2ec744c3bb4fe848542b8ce46b00d161815e64368caeb80ff2bc1512fc",
                    "MinGameVersion" : "4.37.32.833",
                    "Signature" : "31534742c5d19dae41532154f60863f2c7f7e777ee0a4fb3ca541e3bcde8e030baf6893f957eb2bb9b25e907efdcf042f4a698751b53582924e8ae46cccee09269057cac0105312100",
                    "URL" : "https://bg3se-updates.norbyte.dev/Channels/Release/Packages/v7.0.0.0-d52f9b2ec744c3bb4fe848542b8ce46b00d161815e64368caeb80ff2bc1512fc.package",
                    "Version" : "7.0.0.0"
                }
            ]
        }
    ]
}

**Comment by Norbyte** [comment] 2024-05-10 08:30
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.

**Closed by Norbyte** 2024-05-10 08:30 UTC
