### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by emk15** [Norbyte/bg3se#229] opened 2024-01-16 02:57 UTC
Starting or reloading a save will crash the game and show this. What's causing the crash, script extender or is it just telling me?? I really need help. I reinstalled script extender and it crashed again. The game worked yesterday and I didn't touch it until now, so I didn't do anything to cause it by messing in files or mods. Is it from the newest hotfix??
![bandicam 2024-01-15 18-40-17-604](https://github.com/Norbyte/bg3se/assets/156735751/a56fafa1-aae4-49b1-ad10-615c903e6fb7)

**Comment by Norbyte** [comment] 2024-01-16 15:02
What mods are you using?

**Comment by emk15** [comment] 2024-01-16 17:28
Honestly a lot (away from pc so can’t get a list) but I did try taking the mods out and it still crashed. I uninstalled script extender and that actually worked. I need script extender though so I’m not sure where to go from here. I tried doing a fresh install and still crashed.

**Comment by Norbyte** [comment] 2024-01-16 20:44
A potential fix for this issue was released, can you check again to see if it crashes?

**Comment by emk15** [comment] 2024-01-16 23:51
I see the fix but I'm unsure how to download/install it

**Comment by Norbyte** [comment] 2024-05-10 08:50
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.

**Closed by Norbyte** 2024-05-10 08:50 UTC
