### ISSUE TITLE
Game keeps crashing after new patch 

### ISSUE THREAD

**Issue by BitterXsweet** [Norbyte/bg3se#264] opened 2024-02-16 15:15 UTC
My game loads the launcher and allows me to get to the starter menu and loads to about 50% of shaders when I select continue and then crashes, and the crash report is flagging the bg3 script extender as the issue.

![image_2024-02-16_151926295](https://github.com/Norbyte/bg3se/assets/160254743/2f8fe502-fbc7-4509-a40f-99e53e34b7ac)

**Comment by Hermioie** [comment] 2024-02-16 15:17
same problem

**Comment by MarcusWikstrand** [comment] 2024-02-16 15:22
me too! I tried removing all other mods, and the problem persists so long as the latest version of Script extender is installed. (I installed via Mod Manager)

**Comment by linkehan1** [comment] 2024-02-16 15:26
same problem,i tried removing all other mods, and the problem persists so long as the latest version of Script extender is installed. (I installed via Mod Manager)

**Comment by Saturnnd** [comment] 2024-02-16 15:28
You can play if you delete the script extender file but the mods will not work. I am waiting if them update the script extender

**Comment by linkehan1** [comment] 2024-02-16 15:46
Thank you for the quick fixes in advance! I have a long weekend so I’m praying I’ll get to mess around with the new patch 🙏

**Comment by lRis-y** [comment] 2024-02-16 16:00
I delete the DWrite.dll, and I can load the save get in the game But when I try to pick a lock, the game crash

**Comment by JupeMoox** [comment] 2024-02-16 16:05
Exact same here as everyone.. hopefully we can get back to it soon !

**Comment by DaelonDuluc** [comment] 2024-02-16 16:41
Of course it's crashing.  The team will need a little bit to get everything updated to run with Patch #6.  Just be patient. 

They'll come through.  They always do!  :)

**Comment by Diaphin39** [comment] 2024-02-16 17:09
It randomly started crashing for me. I tried to rollback the game so that I can keep on playing until the update is out and it worked at first, but an our later the crashes started happening.

**Comment by DaelonDuluc** [comment] 2024-02-16 17:13
> It randomly started crashing for me. I tried to rollback the game so that I can keep on playing until the update is out and it worked at first, but an our later the crashes started happening.

It happens every update.  Sorry.  They'll have it fixed in a bit.  Me... I'm just play something else for a few hours.  If worse comes to worse it'll be back up by the morning.  

The team is very dependable.

Sometimes I just hop over and play by PS version instead.  Sure... no mods... but it's easy! :)

**Comment by Diaphin39** [comment] 2024-02-16 17:33
> > It randomly started crashing for me. I tried to rollback the game so that I can keep on playing until the update is out and it worked at first, but an our later the crashes started happening.
> 
> It happens every update. Sorry. They'll have it fixed in a bit. Me... I'm just play something else for a few hours. If worse comes to worse it'll be back up by the morning.
> 
> The team is very dependable.
> 
> Sometimes I just hop over and play by PS version instead. Sure... no mods... but it's easy! :)

Thanks for the reply. So there is no way to just rollback? It worked for me at first, I rolled back the way you usually do with Steam Games downloging the files and copying them in and it worked at first, then suddenly started crashing

**Comment by DaelonDuluc** [comment] 2024-02-16 17:36
> > > It randomly started crashing for me. I tried to rollback the game so that I can keep on playing until the update is out and it worked at first, but an our later the crashes started happening.
> > 
> > 
> > It happens every update. Sorry. They'll have it fixed in a bit. Me... I'm just play something else for a few hours. If worse comes to worse it'll be back up by the morning.
> > The team is very dependable.
> > Sometimes I just hop over and play by PS version instead. Sure... no mods... but it's easy! :)
> 
> Thanks for the reply. So there is no way to just rollback? It worked for me at first, I rolled back the way you usually do with Steam Games downloging the files and copying them in and it worked at first, then suddenly started crashing

The only way I know to roll it back is to remove uninstall the game, disable automatic updates for it and then reinstall and only install the updates you want to.  That can take a while though.  I usually just am patient.

**Comment by DaelonDuluc** [comment] 2024-02-16 18:50
> > You can play if you delete the script extender file but the mods will not work. I am waiting if them update the script extender
> 
> do we know how long it will be till its updated?

It'll probably be by EOD but might not be until the morning.  They're usually pretty fast though.

**Comment by Diaphin39** [comment] 2024-02-16 19:00
So I tried it out and I was able to rollback again by repairing the game and then copy in the downloaded content data from Patch 5 back into the BG3 Folder, as well as copying the current BG3SE back in. I guess that will do for being able to play with mods until the new version comes around.

**Comment by jpalioto** [comment] 2024-02-16 22:14
Is there a configuration option to disable auto-updating? That would help. That way, I could load the previous version of SE and finish my playthrough before I update to Patch 6 and the new SE.

**Comment by rmm200** [comment] 2024-02-16 22:31
Looks like current fix - fixed it.
Good job team! I am off and running.

**Comment by jordan-day** [comment] 2024-02-16 22:48
How does this work? I didn't patch my game to patch6, but this morning script extender was crashing..
What happened there?

**Comment by Kyshira** [comment] 2024-02-16 23:01
Everything is fine till I try to lockpick

**Comment by Jephry5** [comment] 2024-02-16 23:17
Same here with lockpicking...wonder what that's about...

**Comment by FabledPasta** [comment] 2024-02-17 00:03
It seems that my GPU useable is spiking when I start a skill check such as lockpicking and my crashlog shows an access violation error related to gameoverlayrenderer64.dll. I don't know how helpful this is or if it's even correct but that's all the infor I could get out of my crashes.

**Comment by Robified0** [comment] 2024-02-17 01:39
For anyone with crashing on skill checks, remove "Improved UI Assets". If you are using Better Containers, make sure you are using their Default version (not the one with UI Assets). Doing this fixed the lockpick issue for me.

**Comment by Leonm99** [comment] 2024-02-17 02:23
> For anyone with crashing on skill checks, remove "Improved UI Assets". If you are using Better Containers, make sure you are using their Default version (not the one with UI Assets). Doing this fixed the lockpick issue for me.

YOOOOO this fixed the  lockpick crash for me thanks alot!!!

**Comment by demobats** [comment] 2024-02-17 02:38
Still crashing out during skill checks, as soon as i select one i crash out. Removing Improved UI Assets didn't work for me.

**Comment by Robified0** [comment] 2024-02-17 04:32
@demobats Must be another mod. Maybe a dice mod? Anything that might have Improved UI Assets as a requirement might need to be removed.

**Comment by demobats** [comment] 2024-02-17 07:08
> @demobats Must be another mod. Maybe a dice mod? Anything that might have Improved UI Assets as a requirement might need to be removed.

that's what i've been seeing but the thing is i haven't got any dice mods on. has to be something that requires ui assets so time to pick through and see whats conflicting. it's either that or my save file is corrupt somehow

**Comment by Norbyte** [comment] 2024-05-10 08:57
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.

**Closed by Norbyte** 2024-05-10 08:57 UTC
