### ISSUE TITLE
Game Not Launching while using BG3SE

### ISSUE THREAD

**Issue by IAVargas** [Norbyte/bg3se#196] opened 2023-12-05 12:43 UTC
I am having an issue with the BG3 Script Extender (October 28 version) where Baldur's Gate 3 fails to open when the extender is installed. I can see the bg3.exe process in the task manager, but there is no activity, and the game window does not open. In contrast, when the Script Extender is not installed, the game opens and runs normally. The game used to launch normally before patch 5, hotfix 12.

This is when SE is installed

<img width="436" alt="Screenshot 2023-12-05 085436" src="https://github.com/Norbyte/bg3se/assets/127046707/a4207f10-2859-4610-91f1-d44f7faf54ad">

This is when SE is not installed and the game is running properly

<img width="435" alt="Screenshot 2023-12-05 085736" src="https://github.com/Norbyte/bg3se/assets/127046707/7e682dac-2eef-4d3a-866c-21006e783e2d">

Environment: 

- OS Windows 11
- Game Version: Patch 5, Hotfix 12
- Using BG3SE October 28 release
- Vortex Mod Manager

Additional Mods in Use:
- Mod Fixer
- Improved UI
- Improved UI Assets
- Gold Zero Weight
- Achievement Enabler BG3AE
- Native Mod Loader
- Bags Bags Bags
- Show Approval Ratings (English)
- LSLib/Divine Tool 

EDIT: Fixed

Thanks to insights from AziosFour who identified a workaround for the issue where the BG3 Script Extender (BG3SE) does not function properly alongside the Native Mod Loader. The solution involves a specific file placement adjustment.

Steps to Resolve the Issue:

Locate the Native Mod Loader folder within the bin directory of Baldur's Gate 3.
Move the DWrite.dll file into the Native Mod Loader folder
This method rectifies the problem of BG3 failing to launch when both BG3SE and the Native Mod Loader are installed.

I want to express my gratitude to AziosFour for finding this solution. Also, a big thank you to everyone who participated in the discussion and offered their insights.

**Comment by n0stalghia** [comment] 2023-12-05 21:46
Duplicate of https://github.com/Norbyte/bg3se/issues/195

**Comment by n0stalghia** [comment] 2023-12-05 21:54
Was able to reproduce the issue on a Windows 10 machine. Same configuration, just a different OS - not that I thought it would matter.

**Comment by joffie87** [comment] 2023-12-05 23:07
I have this issue as well. Removing Native Mod Loader allows my game to load.

Enviroment: 

OS Windows 10
Game Version: Patch 5, Hotfix 12
Using BG3SE October 28 release
BG3MM

**Comment by n0stalghia** [comment] 2023-12-07 21:12
> It happens because native mod loader and script extender tries to load at the same time, for me it happened with gog version I bought steam and no longer happens others its the opposite..
> 
> However it CAN launch, you need to kill the game in task manager and keep trying to launch it, can take up to 15 tries but it will launch with both of them installed

Sounds plausible. After trying to launch BG3 using Script Extender + Native Mod Loader, after ~30 tries, it managed to start on both my Win 10 and Win 11 systems.

**Comment by Galthariel** [comment] 2023-12-08 00:44
This conclusion came after several tests and troubleshooting. While it is true that deleting BG3SE or NML makes the game launch it seems that what is causing the issue is another mod that uses NML which in my case was Achievement Enabler (BG3AchievementEnabler.dll). Deleting that dll from the Native Mods folder fixed the issue. As I said, In my case, it was Achievement Enabler but it could be any other mod that requires NML.

I hope that helps.

**Comment by Proclus01** [comment] 2023-12-10 13:33
I found how to resolve the issue, at least on my system. For context, I have no other mods installed, and I installed BG3SE by copying the DLL and JSON files. So, it was a clean install. 

The Lari Launcher is what prevents you from launching the game when you have BG3SE in the /bin folder. 

The solution for a Steam-installed game is to go to steam, right click the game, go into Properties, and enter into the launch param field the following "--skip-launcher". 

With this added, the game now launches with BG3SE without fail. There may be additional workarounds of a similar sort if you installed it via GOG or another portal, but I have not tried these out.

**Comment by Juub1990** [comment] 2023-12-30 05:38
I got it working by using Vulkan instead of DX11.

**Comment by Rappeldrache** [comment] 2024-01-07 00:07
I still have the problem: SE and Native Mod Loader - Mods don't work together. Somebody know a solution?

I really, really wan to play with the WASD & Camera Mod.

"--skip-launcher" dit not help. :(

**Comment by Galthariel** [comment] 2024-01-07 01:49
> I still have the problem: SE and Native Mod Loader - Mods don't work together. Somebody know a solution, please? I use the BG3 ModManager. :) I really, really want to play with the WASD & Camera Mod. And of course with a lot more SE - Mods.
> 
> "--skip-launcher" dit not help. :(

Are you using Achievement Enabler? If yes, use the test version from the Addon comments in Nexus. If not try to check all the comments under WASD and Camera Mod and see if you find something in there. I don't use WASD but had the same issue and the issue was the Achievement Enabler.

**Comment by n0stalghia** [comment] 2024-01-07 08:53
> I still have the problem: SE and Native Mod Loader - Mods don't work together. Somebody know a solution, please? I use the BG3 ModManager. :) I really, really want to play with the WASD & Camera Mod. And of course with a lot more SE - Mods.
> 
> "--skip-launcher" dit not help. :(

Disabling "Achievement Enabler" and updating the script extender allowed me to play. I've played in my save with WASD Movement + Native Camera Tweaks + Bags Bags Bags in the most recent patch as of December 7th, 2024, without issue.

**Comment by Rappeldrache** [comment] 2024-01-07 12:36
Thanks for the answer :)
I never had the Achivement Enabler .... and still got the problem. :(
I read till days in the comment sections at the WASD, the Camera and the Native Mod Loader section. Also the comment section of the Script Extender. I also asked there. Seam like some other people have the same problem as me.

**Comment by AziosFour** [comment] 2024-01-09 06:24
I have the same issue, I moved DWrite.dll to my bin folder and its working with Camera&WASD, AchievementEnabler in the same folder, and Transmog enhance mods is working with SE.

**Comment by Rappeldrache** [comment] 2024-01-09 20:35
DWrite.dll is always in my bin folder. Dit you move ALL Camera&WASD Files also into the bin folder? Cause right now a few of them are in the "Native Mods" folder.

**Comment by AziosFour** [comment] 2024-01-09 22:27
> DWrite.dll is always in my bin folder. Dit you move ALL Camera&WASD Files also into the bin folder? Cause right now a few of them are in the "Native Mods" folder.

Sorry i meant Nativemod folder, and mod manager show like SE is missing but i can open the game and its working fine
![image_2024-01-09_162708858](https://github.com/Norbyte/bg3se/assets/156055434/9cbf5649-f43a-49ae-8a20-f1b23776a500)

**Comment by Rappeldrache** [comment] 2024-01-10 11:50
So you DWrite.dll is NOT in your bin folder, it is in the bin/NativeMods folder? 

(This could be a solution .... if it works)

**Comment by thattguy23** [comment] 2024-02-23 10:51
> So you DWrite.dll is NOT in your bin folder, it is in the bin/NativeMods folder?
> 
> (This could be a solution .... if it works)

THIS  WAS THE ANSWER FOR ME

**Closed** 2024-02-27 22:08 UTC
