### ISSUE TITLE
ScriptExtender Errors after uptdate to BG3 version v4.1.1.3767641

### ISSUE THREAD

**Issue by Pikas62** [Norbyte/bg3se#106] opened 2023-10-17 15:16 UTC
After the last update to BG3 version v4.1.1.3767641 I get the error message in game: "An error has occurred during Scipt Extender initialization. Some extension features might be unavailable". I can no longer do fast travel and I can no longer get to the camp. I use the current version of the Script Extender Laucher and the BG3 Mod Manager.Bolow the log of the script extender.

Any ideas?

Script Extender Log:
******************************************************************************
*                                                                            *
*                     BG3 Script Extender Debug Console                      *
*                                                                            *
******************************************************************************
BG3Ext v7 built on Oct  8 2023 18:45:00
Game version v4.37.67.641 OK
ScriptExtender::Initialize: Starting
No match found for mapping 'esv::SavegameManager::WarnIfModded'
No match found for mapping 'esv::SavegamePostVisit_DisableStoryMerge'
No match found for mapping 'esv::StatsSystem::ThrowDamageEvent'
No match found for mapping 'ecs::ComponentIDRef'
No match found for mapping 'ecs::EventComponentIDRef'
No match found for mapping 'ecs::ReplicationComponentIDRef2'
No match found for mapping 'KillLauncher'
Library startup took 995 ms
No match found for mapping 'eoc::SpellPrototype::Init Outer'
LibraryManager::PostStartupFindLibraries() took 145 ms
bg3se::ecs::EntitySystemHelpersBase::MapComponentIndices(): Could not find index for component: eoc::spell::CastComponetbg3se::ecs::EntitySystemHelpersBase::MapComponentIndices(): Could not find index for component: eoc::spell::CastComponetSTARTUP ERROR: An error has occurred during Script Extender initialization. Some extension features might be unavailabl.Configuration for 'Daughter of Lolth - Chosen Path':
        MinVersion 2; Feature flags: Lua
1 mod configuration(s) loaded.
Merged configuration:
        MinVersion 2; Feature flags: Lua
Initializing client with target context Load
Modded achievements enabled.
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
Configuration for 'Daughter of Lolth - Chosen Path':
        MinVersion 2; Feature flags: Lua
1 mod configuration(s) loaded.
Merged configuration:
        MinVersion 2; Feature flags: Lua
Initializing client with target context Game
bg3se::ExtensionStateBase::LuaResetInternal(): LUA VM reset.
ecl::ScriptExtender::OnGameStateChanged(): Loaded module

**Comment by BelegCufea** [comment] 2023-10-17 17:54
@Pikas62 This is a problem with Vulkan binary (bg3.exe). Try DX11 one (bg3_dx11.exe).
See #94

**Comment by TheoGeek** [comment] 2023-10-17 20:10
Do you know if there is going to be an attempt to "fix it" in the script extender or is the Vulkan build or would it have to be fixed in the bg3 Vulkan build?

**Comment by BelegCufea** [comment] 2023-10-17 20:40
@TheoGeek
For some reason Script Extender stopped working for me with BG3 Hotfix 7 on GOG Vulkan executable. Without any change in ScriptExtender code it worked fine with Hotfix 8. And again without any change on ScriptExtender side it stopped working with Hotfix 9.
I have no idea how ScriptExtender works (I can use barely desktop calculator to sum two numbers) so I can't say what is the problem. Norbyte (SE author) is working his ass out to make it function in as many situatuons as possible but sometimes there are issues he can't reproduce.
I am just fine using DX11 executable (althought it is not as smooth as Vulkan for me) for the time being. Let's have a faith :-)

**Comment by TheoGeek** [comment] 2023-10-17 20:45
@BelegCufea - I 100% agree that Norbyte is the man, I can be patient. :)

**Comment by Pikas62** [comment] 2023-10-18 05:31
Thank you for the feedback! With the DX11 executable it runs without any problems.

**Comment by dpedrinha** [comment] 2023-10-27 21:30
It was working fine earlier today but I just started getting this error. Always used DX11.

**Comment by dredog11** [comment] 2023-10-27 22:59
> It was working fine earlier today but I just started getting this error. Always used DX11.

Same for me, it even worked earlier today and now this afternoon it is no longer working.  I don't show there was an update to BG3 either.

**Comment by dpedrinha** [comment] 2023-10-27 23:01
> > It was working fine earlier today but I just started getting this error. Always used DX11.
> 
> Same for me, it even worked earlier today and now this afternoon it is no longer working. I don't show there was an update to BG3 either.

Game version is still v4.1.1.3767641 for me, so no game update.

**Comment by BelegCufea** [comment] 2023-10-28 07:43
See #118 It may be another error you are getting. If not check if you really use DX11 executable.

**Comment by dpedrinha** [comment] 2023-10-31 00:08
> See #118 It may be another error you are getting. If not check if you really use DX11 executable.

That would be correct. Thank you.

**Comment by Norbyte** [comment] 2024-05-10 08:35
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.

**Closed by Norbyte** 2024-05-10 08:35 UTC
