### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Flerkisa** [Norbyte/bg3se#115] opened 2023-10-25 16:33 UTC
When I try to use Improved UI mod I always get the same error and mod doesn't work partially. I only use two other mods and they work fine, I have no idea what could be the issue.

BG3Ext v7 built on Oct  8 2023 18:45:00
Game version v4.37.67.641 OK
ScriptExtender::Initialize: Starting
No match found for mapping 'esv::SavegameManager::WarnIfModded'
No match found for mapping 'esv::SavegamePostVisit_DisableStoryMerge'
No match found for mapping 'esv::StatsSystem::ThrowDamageEvent'
No match found for mapping 'ecs::ComponentIDRef'
No match found for mapping 'ecs::EventComponentIDRef'
No match found for mapping 'ecs::ReplicationComponentIDRef2'
No match found for mapping 'KillLauncher'
Library startup took 3451 ms
No match found for mapping 'eoc::SpellPrototype::Init Outer'
LibraryManager::PostStartupFindLibraries() took 391 ms
bg3se::ecs::EntitySystemHelpersBase::MapComponentIndices(): Could not find index for component: eoc::spell::CastComponent
bg3se::ecs::EntitySystemHelpersBase::MapComponentIndices(): Could not find index for component: eoc::spell::CastComponent
STARTUP ERROR: An error has occurred during Script Extender initialization. Some extension features might be unavailable.

**Comment by BelegCufea** [comment] 2023-10-26 06:42
Seems like duplicate of #87. Try running DX11 executable to see if it helps.

**Comment by Flerkisa** [comment] 2023-10-26 07:30
Oh I get it now, it was the mod manager issue, for some reason it was launching bg3.exe instead of bg3_dx11.exe. Yeah, seems to work now.

**Comment by Norbyte** [comment] 2024-05-10 08:36
I'm closing old issues related to old game versions, since those were largely fixed by later game patches and SE updates and are no longer relevant/reproducible.

**Closed by Norbyte** 2024-05-10 08:36 UTC
