### ISSUE TITLE
SOLVED Console won't open, SE works

### ISSUE THREAD

**Issue by SilverExil** [Norbyte/bg3se#327] opened 2024-02-28 07:29 UTC
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

After installing SE I can start the game and mods work, but the console won't appear. I have the ScriptExtenderSettings.json and I even exchanged it for the one in the downloadable package. Problem appeared even without mods, mods were only activated as a test whether they(and in reverse SE) work.

**Comment by Varriount** [comment] 2024-02-28 23:03
Could you please run the [diagnostic script](https://github.com/Norbyte/bg3se/blob/main/Generate%20BG3%20Diagnostic.bat) and attach the results? Without more information on what files are present in your installation, it's hard to tell what could be the cause.

**Comment by SilverExil** [comment] 2024-02-29 08:07
Thanks for the fast reply, this should be it.
[BG3 Diagnostic Data.txt](https://github.com/Norbyte/bg3se/files/14444817/BG3.Diagnostic.Data.txt)

**Comment by Varriount** [comment] 2024-02-29 19:59
I'm not seeing your ScriptExtenderSettings.json file in the diagnostic. Where are you plancing it?

**Comment by SilverExil** [comment] 2024-02-29 20:03
> I'm not seeing your ScriptExtenderSettings.json file in the diagnostic. Where are you plancing it?

![image](https://github.com/Norbyte/bg3se/assets/47903581/a41155e4-2b65-4576-bb99-5dc16eb809c4)
In the bin folder

**Comment by SilverExil** [comment] 2024-03-01 06:18
Could that be the error, that my Settings.json is not being found?

**Comment by cprell** [comment] 2024-03-01 21:33
To add to this, I am not using any mods and I also can't get it to work. 

Here's my log. ScriptExtenderSettings.json is found by the diagnostics.

[BG3 Diagnostic Data.txt](https://github.com/Norbyte/bg3se/files/14466186/BG3.Diagnostic.Data.txt)

No console on startup.

**Comment by Varriount** [comment] 2024-03-02 00:15
Can you post the contents of your settings files? Make sure they're valid JSON (commas in the correct places, etc.)

**Comment by SilverExil** [comment] 2024-03-02 05:39
> Can you post the contents of your settings files? Make sure they're valid JSON (commas in the correct places, etc.)

{
  "CreateConsole": true
}

**Comment by Varriount** [comment] 2024-03-02 06:14
@cprell Two odd things:
  - Your diagnostic file doesn't appear to find all the files normally found in the game's installation and state directories.
  - You don't appear to have any mods enabled. Are you sure that Script Extender is actually being loaded?

@SilverExil Based on that image, I can't be sure whether Script Extender's settings file and main DLL are in the correct location. For reference, if you bought the game from Steam, you normally need to place both files in `C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin\`. This might differ if you've installed the game to a custom location, such as a secondary hard disk.

**Comment by SilverExil** [comment] 2024-03-02 06:23
"D:\SteamLibrary\steamapps\common\Baldurs Gate 3\bin\ScriptExtenderSettings.json"

"D:\SteamLibrary\steamapps\common\Baldurs Gate 3\bin\DWrite.dll"

The second screenshot was for reference regarding the installation package.

**Comment by SilverExil** [comment] 2024-03-02 06:31
Reloaded over vortex this time, same problem but 3 additional paragraphs in the diagnostic data.
MD5       7F59E421F82D66545D8922578A144175 C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin\DWrite.dll
MD5       4E9191AC38E77D013373071207019F9C C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin\steam_appid.txt  
MD5       A37EC9C3D6A8E75F2D3CDF7C64E0C66D C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3\bin\vortex.deployment.bg3-bg3se.json 

A few others changed the string after MD5. That's all.
New file.
[BG3 Diagnostic Data New.txt](https://github.com/Norbyte/bg3se/files/14468316/BG3.Diagnostic.Data.New.txt)

**Comment by Varriount** [comment] 2024-03-02 22:36
@SilverExil Wait, so is your BG3 installation at `D:\SteamLibrary\steamapps\common\Baldurs Gate 3` or `C:\Program Files (x86)\Steam\steamapps\common\Baldurs Gate 3`?

**Comment by SilverExil** [comment] 2024-03-03 02:36
Yes, that's my installation. On a second hard drive, officially downloaded there via steam(never moved the installation).

**Comment by SilverExil** [comment] 2024-03-03 15:54
Thanks to @Varriount for the help. It was a steam sided error and BG3 was installed on both hard drives and messing with the SE. Removed the wrong one and now it works.

**Comment by Varriount** [comment] 2024-03-03 19:35
@SilverExil If your problem is fixed, you can close the issue.

**Closed** 2024-03-03 19:37 UTC
